# General Settings
name: Egor Bogatov
job_title: Developer at Microsoft
description: C#, C++, Performance
avatar: /ava.png
favicon: /favicon.ico
twitter_handler: egorbo
analytics_code: UA-XXXXXXX-2
disqus: egorbo

# Social Accounts
social_networks:
-  { name: twitter, url: 'http://twitter.com/EgorBo' }
-  { name: github, url: 'http://github.com/EgorBo' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 0
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

